config/routes.rb
Rails.application.routes.draw do

  # 顧客用　devise
  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用 devise
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    resources :musics
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :members, only: [:create, :destroy]
    end
  end

  # admin側のルーティング設定
  namespace :admin do
    get 'top' => 'homes#top'
    patch 'top' => 'homes#update'
    delete 'top' => 'homes#destroy'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      member do
        patch 'change_up'
        patch 'change_down'
      end
      resources :members, only: [:create, :destroy]
    end
    resources :musics, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'timetable'
      end
    end

  end

end

app/models/band.rb
class Band < ApplicationRecord

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :musics, dependent: :destroy
  has_many :users, through: :musics

  validates :band_name, presence: true
  validates :mike_number, presence: true
end

app/controllers/admin/bands_controller.rb
class Admin::BandsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @band = Band.new
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
    @member = @band.members.new
    @users = User.all
  end

  def edit
    @band = Band.find(params[:id])
  end

  def create
    @bands = Band.all
    @band = Band.new(band_params)
    @band.linenumber = Band.count + 1
    if Band.where(band_name: @band.band_name).count == 0
      if @band.save
        redirect_to admin_bands_path
      else
        render :index
      end
    else
      flash[:name] = "既にバンドが存在しています。"
      render :index
    end
  end

  def change_up
    @band = Band.find(params[:id])
    @before_band = Band.where("linenumber < ?", @band.linenumber).order("linenumber desc").first(1)
      @before_band.each do |band|
        @before_linenumber = @band.linenumber
        @target_linenumber = band.linenumber
        band.linenumber = @before_linenumber
        @band.linenumber = @target_linenumber
        @band.update(band_linenumber_params)
        band.update(band_linenumber_params)
      end
    redirect_to timetable_admin_musics_path
  end
  
  def change_down
    @band = Band.find(params[:id])
    @before_band = Band.where("linenumber > ?", @band.linenumber).order("linenumber").first(1)
      @before_band.each do |band|
        @before_linenumber = @band.linenumber
        @target_linenumber = band.linenumber
        band.linenumber = @before_linenumber
        @band.linenumber = @target_linenumber
        @band.update(band_linenumber_params)
        band.update(band_linenumber_params)
      end
    redirect_to timetable_admin_musics_path
  end

  def update
     @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to admin_band_path(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to admin_bands_path
  end


  private

  def band_params
    params.require(:band).permit(:band_name, :mike_number, :other, :linenumber)
  end

   def band_linenumber_params
    params.permit(:linenumber)
  end

end

app/helpers/admin/bands_helper.rb
module Admin::BandsHelper
end

app/views/admin/bands/_member.html.erb
<% band.members.each do |member| %>
  <% if member.user.present? %>
    <%= member.user.nickname %>　<%= link_to "消去", admin_band_member_path(band.id, member.user_id), method: :delete, remote: true %></br>
  <% end %>
<% end %>

app/views/admin/bands/edit.html.erb
<%= render 'layouts/error_messages', model: @band %>
<div class="container">
  <div class="row">
  	<div class="col-7 mx-auto pt-5">
  	  <h2 class="text-center p-3"><b>バンド情報編集</b></h2>
  	  <%= form_with model: @band, url: admin_band_path, method: :patch do |f| %>
  	    <div class="form-group col-12 p-1">
  	      <%= f.label :"バンド名", class: "col-5" %>
  	  	  <%= f.text_field :band_name %>
  			</div>
  			<div class="form-group col-12 p-1">
          <%= f.label :"使用マイク本数", class: "col-5" %>
          <%= f.select :mike_number , [ [1,1], [2, 2], [3, 3 ] ,[4, 4], [5, 5] ], prompt: "マイクの使用本数" %>
        </div>
        <div class="form-group col-12 p-1">
  	      <%= f.label :"備考", class: "col-5" %>
  	  	  <%= f.text_area :other %>
  			</div>

  			<div class="actions text-center p-3">
  	  	  <%= f.submit "編集内容を登録", class: "btn btn-lg bg-dark rounded-pill text-info" %>
  			</div>
  		<% end %>
    </div>
  </div>
</div>

app/views/admin/bands/index.html.erb
<%= render 'layouts/error_messages', model: @band %>

<div class="container">
  <div class="row">
  	<div class="col-6 mx-auto pt-5">
  	  <h2 class="text-center p-3"><b>バンド登録</b></h2>
  	  <h5 class="text-danger text-center"><%= flash[:name] %></h5>
  	  <%= form_with model: @band, url: admin_bands_path, method: :post do |f| %>
  	    <div class="form-group col-12 p-1">
  	      <%= f.label :"バンド名", class: "col-6" %>
  	  	  <%= f.text_field :band_name %>
  			</div>
  			<div class="form-group col-12 p-1">
          <%= f.label :"マイク本数", class: "col-6" %>
          <%= f.select :mike_number , [ [1,1], [2, 2], [3, 3 ] ,[4, 4], [5, 5] ], prompt: "マイクの使用本数" %>
        </div>
        <div class="form-group col-12 p-1">
  	      <%= f.label :"備考", class: "col-6" %>
  	  	  <%= f.text_area :other %>
  			</div>

  			<div class="actions text-center p-3">
  	  	  <%= f.submit "バンドを登録", class: "btn btn-lg bg-dark rounded-pill text-info" %>
  			</div>
  		<% end %>
  	</div>
  	<div class="col-6 mx-auto pt-5 pb-5">
  	  <h2 class="text-center p-3"><b>バンド一覧</b></h2>
  	  <table class="table table-hover table-bordered table-condensed text-center">
        <thead>
          <tr class="text-light bg-dark">
            <th>バンド名</th>
            <th>メンバー数</th>
          </tr>
        </thead>
        <tbody>
          <% @bands.each do |band| %>
            <tr class="bg-light">
              <td class="col-auto">
                <%= link_to admin_band_path(band) do %>
                  <%= band.band_name %>
                <% end %>
              </td>
              <td class="col-auto">
                <i class="fa-solid fa-users"></i>　<%= band.members.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  	</div>
  </div>
</div>

app/views/admin/bands/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 text-center mx-auto pt-5">
      <h2 class="p-3"><b><%= @band.band_name %> 詳細</b></h2>
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <tr class="text-light bg-dark">
            <th>項目</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <tr class="bg-light">
            <td class="col-auto">
              バンド名
            </td>
            <td class="col-auto">
              <%= @band.band_name %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              使用マイク本数
            </td>
            <td class="col-auto">
              <%= @band.mike_number %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              備考
            </td>
            <td class="col-auto">
              <%= @band.other %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              メンバー
            </td>
            <td class="col-auto" id="members">
              <%= render 'admin/bands/member', band: @band %>
            </td>
          </tr>

        </tbody>
      </table>
      <div class="text-center p-3">
        <%= link_to edit_admin_band_path(@band), class: "btn btn-lg bg-dark rounded-pill text-success mr-5" do %>
          <b>編集</b>
        <% end %>
        <%= link_to admin_band_path(@band), method: :delete, class: "btn btn-lg bg-dark rounded-pill text-danger ml-5", "data-confirm" => "本当に消しますか？" do %>
          <b>消去</b>
        <% end %>
      </div>
    </div>
    <div class="col-5 text-center mx-auto pt-5">
      <h2 class="p-3"><b>メンバー 追加</b></h2>
      <div class="form-group col-12 p-2">
        <%= form_with model: @member, url: admin_band_members_path(@band), method: :post, local: false do |f| %>
          <%= f.select :user_id, options_from_collection_for_select(@users, :id, :nickname), include_blank: "選択してください" %>
          <%= f.submit "追加", class: "btn btn-info col-xs-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>