config/routes.rb
Rails.application.routes.draw do

  # 顧客用　devise
  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用 devise
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    resources :musics
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :members, only: [:create, :destroy]
    end
  end

  # admin側のルーティング設定
  namespace :admin do
    get 'top' => 'homes#top'
    patch 'top' => 'homes#update'
    delete 'top' => 'homes#destroy'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      member do
        patch 'change_up'
        patch 'change_down'
      end
      resources :members, only: [:create, :destroy]
    end
    resources :musics, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'timetable'
      end
    end

  end

end

app/models/music.rb
class Music < ApplicationRecord
  
  belongs_to :user
  belongs_to :band
  
  validates :music_name, presence: true
  validates :music_time, presence: true
  validates :band_id, presence: true
  
end

app/controllers/admin/musics_controller.rb
class Admin::MusicsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @musics = Music.page(params[:page]).per(20)
  end

  def show
    music = Music.find(params[:id])
    @music = Music.find_by(user_id: music.user_id)
    @musics = Music.where(user_id: music.user_id)
  end

  def edit
    @music = Music.find(params[:id])
    @bands = Band.all
  end

  def timetable
    @bands = Band.order("linenumber")
    @admin = Admin.find(1)
    @admintime = @admin.start_time
    @conversion_time = @admin.conversion_time*60
  end



  def update
    @music = Music.find(params[:id])
    if @music.update(music_params)
      redirect_to admin_music_path(@music)
    else
      @bands = Band.all
      render :edit
    end
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to admin_musics_path
  end

  private

  def music_params
    params.require(:music).permit(:user_id, :band_id, :music_name, :music_time, :status)
  end

end

app/helpers/admin/musics_helper.rb
module Admin::MusicsHelper
end

app/views/admin/musics/edit.html.erb
<%= render 'layouts/error_messages', model: @music %>

<h2 class="head-line title_h2 text-center pt-5"><b><%= @music.user.nickname %>さん　曲出し編集</b></h2>
<div class="container">
  <div class="row">
	<div class="col-7 mx-auto pt-3">
	  <%= form_with model: @music, url: admin_music_path, method: :patch do |f| %>
		<div class="form-group col-12 p-1">
	      <%= f.label :"曲名", class: "col-6" %>
	  	  <%= f.text_field :music_name %>
		</div>

		<div class="form-group col-12 p-1">
	  	  <%= f.label :"曲時間", class: "col-6" %>
	  	  <%= f.number_field :music_time, min: 1, max: 30 %>
		</div>

		<div class="form-group col-12 p-1">
	      <%= f.label :"出場バンド名", class: "col-6" %>
	  	  <%= f.select :band_id, options_from_collection_for_select(@bands, :id, :band_name) %>
		</div>

		<div class="form-group col-12 p-1">
	      <%= f.label :"公開設定", class: "col-6" %>
	  	  <%= f.radio_button :status, "false" %>
	  	  <%= f.label :"公開" %>
	  	  <%= f.radio_button :status, "true" %>
	  	  <%= f.label :"非公開" %>
		</div>

		<div class="actions text-center p-3">
		  <%= f.submit "編集内容をを登録", class: "btn btn-lg bg-dark rounded-pill text-success" %>
		</div>
	  <% end %>
	</div>
  </div>
</div>

app/views/admin/musics/index.html.erb
<h2 class="text-center title_h2 text-center pt-5"><b>曲出し一覧</b></h2>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mx-auto pt-3 pb-5">
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <tr class="text-light bg-dark">
            <th>ユーザー</th>
            <th>バンド名</th>
            <th>曲名</th>
            <th>曲時間</th>
          </tr>
        </thead>
        <tbody>
          <% @musics.each do |music| %>
            <tr class="bg-light">
              <td class="col-auto">
                <%= link_to admin_music_path(music) do %>
                  <%= music.user.nickname %>
                <% end %>
              </td>
              <td class="col-auto">
                <%= music.band.band_name %>
              </td>
              <td class="col-auto">
                <%= music.music_name %>
              </td>
              <td class="col-auto">
                <%= music.music_time %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @musics %>
    </div>
  </div>
</div>

app/views/admin/musics/show.html.erb
<h2 class="head-line title_h2 text-center pt-5"><b><%= @music.user.nickname %>さん 曲出し詳細</b></h2>
<div class="container">
  <div class="row">
    <div class="col-9 text-center mx-auto pt-3">
      <% @musics.each do |music| %>
        <table class="table table-hover table-bordered table-condensed">
          <thead>
            <tr class="text-light bg-dark">
              <th>曲出し</th>
              <th>内容</th>
            </tr>
          </thead>
          <tbody>
            <tr class="bg-light">
              <td class="col-auto">
                曲名
              </td>
              <td class="col-auto">
                <%= music.music_name %>
              </td>
            </tr>
  
            <tr class="bg-light">
              <td class="col-auto">
                曲時間
              </td>
              <td class="col-auto">
                <%= music.music_time %>
              </td>
            </tr>
  
            <tr class="bg-light">
              <td class="col-auto">
                バンド名
              </td>
              <td class="col-auto">
                <%= music.band.band_name %>
              </td>
            </tr>
  
            <tr class="bg-light">
              <td class="col-auto">
                公開設定
              </td>
              <td class="col-auto">
                <% if music.status == false %>
                  公開
                <% else %>
                  非公開
                <% end %>
              </td>
            </tr>
  
          </tbody>
        </table>
        <div class="text-center p-3">
          <%= link_to edit_admin_music_path(music), class: "btn btn-lg bg-dark rounded-pill text-success mr-5 mb-5" do %>
            <b>編集</b>
          <% end %>
          <%= link_to admin_music_path(music), method: :delete, class: "btn btn-lg bg-dark rounded-pill text-danger ml-5 mb-5", "data-confirm" => "本当に消しますか？" do %>
            <b>消去</b>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/musics/timetable.html.erb
<h1 class="head-line title_h2 text-center pt-5"><b>タイムテーブル</b></h1>
<h3 class="head-line title_h2 text-center pt-3"><b>開始/終了 <%= @admin.start_time.strftime("%H:%M") %>〜<%= @admin.finish_time.strftime("%H:%M") %>　転換時間 <%= @admin.conversion_time %>分</b></h3>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mx-auto pt-4">
      <table class="table table-hover table-bordered table-condensed text-center">
        <thead>
          <tr class="text-light bg-dark">
            <th>バンド名</th>
            <th>バンド曲数</th>
            <th>バンド持ち時間</th>
            <th>タイムスケジュール</th>
            <th>並び替え</th>
          </tr>
        </thead>
        <tbody>
          <% @over_time = 0 %>
          <% @bands.each_with_index do |band, idx| %>
            <tr class="bg-light">
              <td class="col-auto">
                <%= link_to admin_band_path(band) do %>
                  <%= band.band_name %>
                <% end %>
              </td>

              <td class="col-auto">
                <%= band.musics.count %>
              </td>

              <td class="col-auto">
                <%= (band.musics.sum(:music_time).to_i/5+1)*5 %>
              </td>

              <td class="timetable col-auto">
                <% require "active_support/time" %>
                <% target_band_time = ((Band.find_by(linenumber: idx + 1).musics.sum(:music_time).to_i/5+1)*5)*60 %>
                <b><%= (@admintime + @over_time).strftime("%H:%M") %> ~ <%= (@admintime + @over_time + target_band_time).strftime("%H:%M") %></b>
                <% @over_time = @over_time + target_band_time + @conversion_time %>
              </td>

               <td class="col-auto">
                <%= link_to change_up_admin_band_path(band), method: :patch do %>
                  <i class="fa-solid fa-circle-up"></i>
                <% end %>
                 |
                <%= link_to change_down_admin_band_path(band), method: :patch do %>
                  <i class="fa-solid fa-circle-down"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  	</div>
  </div>
</div>