config/routes.rb
Rails.application.routes.draw do

  # 顧客用　devise
  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用 devise
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    resources :musics
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :members, only: [:create, :destroy]
    end
  end

  # admin側のルーティング設定
  namespace :admin do
    get 'top' => 'homes#top'
    patch 'top' => 'homes#update'
    delete 'top' => 'homes#destroy'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      member do
        patch 'change_up'
        patch 'change_down'
      end
      resources :members, only: [:create, :destroy]
    end
    resources :musics, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'timetable'
      end
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :members, dependent: :destroy
  has_many :bands, through: :members
  
  has_many :musics, dependent: :destroy
  has_many :bands, through: :musics
  
  has_one_attached :image
  
  validates :email, presence: true
  validates :name, presence: true
  validates :nickname, presence: true

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @members = Member.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :introduction, :image)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<%= render 'layouts/error_messages', model: @user %>

<div class="container">
  <div class="row">
  	<div class="col-9 mx-auto pt-5">
  	  <h2 class="text-center pb-4"><b><%= @user.nickname %>さん 編集画面</b></h2>
  	  <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
    	  <div class="form-group col-12 p-1">
    	    <%= f.label :"プロフィール画像", class: "col-6" %>
    	  	<%= f.file_field :image, accept: "image/*", autofocus: true, autocomplete: "image" %>
    		</div>
  
    		<div class="form-group col-12 p-1">
    	    <%= f.label :"氏名", class: "col-6" %>
    	  	<%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    		</div>
  
    		<div class="form-group col-12 p-1">
    	    <%= f.label :"表示名", class: "col-6" %>
    	  	<%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" %>
    		</div>
  
    		<div class="form-group col-12 p-1">
    	    <%= f.label :"メールアドレス", class: "col-6" %>
    	  	<%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    		</div>
  
    		<div class="form-group col-12 p-1">
    	  	<%= f.label :"紹介文", class: "col-6" %>
    	  	<%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
    		</div>
  
    		<div class="actions text-center p-3">
    	  	<%= f.submit "編集内容を登録", class: "btn btn-lg bg-dark rounded-pill text-info" %>
    		</div>
  	  <% end %>
  	</div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center mx-auto pt-5 pb-5">
      <h2 class="text-center pb-4"><b>ユーザー 一覧</b></h2>
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <tr class="text-light bg-dark">
            <th>プロフィール画像</th>
            <th>氏名</th>
            <th>表示名</th>
            <th>メールアドレス</th>
            <th>自己紹介文</th>
            <th>アカウント作成日</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="bg-light">
              <td class="col-auto">
                <% if user.image.attached? %>
                  <%= image_tag user.image, size: "60x60" %>
                <% else %>
                  <%= image_tag 'no_image.jpg', size: "60x60" %>
                <% end %>
              </td>
              <td class="col-auto">
                <%= link_to admin_user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td class="col-auto">
                <%= user.nickname %>
              </td>
              <td class="col-auto">
                <%= user.email %>
              </td>
              <td class="col-auto">
                <%= user.introduction %>
              </td>
              <td class="col-auto">
                <%= user.created_at.strftime("%m/%d") %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<h2 class="head-line title_h2 text-center pt-5"><b><%= @user.nickname %>さん ユーザー詳細</b></h2>
<div class="container">
  <div class="row">
    <div class="col-7 text-center mx-auto pt-3">
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <tr class="text-light bg-dark">
            <th>ユーザー情報</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <tr class="bg-light">
            <td class="col-auto">
              プロフィール画像
            </td>
            <td class="col-auto">
              <% if @user.image.attached? %>
                <%= image_tag @user.image, size: "60x60" %>
              <% else %>
                <%= image_tag 'no_image.jpg', size: "60x60" %>
              <% end %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              氏名
            </td>
            <td class="col-auto">
              <%= @user.name %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              表示名
            </td>
            <td class="col-auto">
              <%= @user.nickname %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              メールアドレス
            </td>
            <td class="col-auto">
              <%= @user.email %>
            </td>
          </tr>

          <tr class="bg-light">
            <td class="col-auto">
              紹介文
            </td>
            <td class="col-auto">
              <%= @user.introduction %>
            </td>
          </tr>

        </tbody>
      </table>
      <div class="text-center pt-3">
        <%= link_to edit_admin_user_path(@user), class: "btn btn-lg bg-dark rounded-pill text-success mr-3" do %>
          <b>編集</b>
        <% end %>
        <%= link_to admin_user_path(@user), method: :delete, class: "btn btn-lg bg-dark rounded-pill text-danger ml-5", "data-confirm" => "本当に消しますか？" do %>
          <b>消去</b>
        <% end %>
      </div>
    </div>
    <div class="col-5 text-center mx-auto pt-3">
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <tr class="text-light bg-dark">
            <th>出場バンド</th>
            <th>メンバー数</th>
          </tr>
        </thead>
        <tbody>
          <% @members.each do |member| %>
            <tr class="bg-light">
              <td class="col-auto">
                <%= link_to admin_band_path(member.band.id) do %>
                  <%= member.band.band_name %>
                <% end %>
              </td>
              <td class="col-auto">
                <i class="fa-solid fa-users"></i>　<%= member.band.members.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>