config/routes.rb
Rails.application.routes.draw do

  # 顧客用　devise
  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用 devise
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    resources :musics
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :members, only: [:create, :destroy]
    end
  end

  # admin側のルーティング設定
  namespace :admin do
    get 'top' => 'homes#top'
    patch 'top' => 'homes#update'
    delete 'top' => 'homes#destroy'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bands, only: [:index, :show, :edit, :create, :update, :destroy] do
      member do
        patch 'change_up'
        patch 'change_down'
      end
      resources :members, only: [:create, :destroy]
    end
    resources :musics, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'timetable'
      end
    end

  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer02">
  <ul class="menu">
    <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-tiktok"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-line"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-github"></i></a></li>
    <li>　　<i class="fa-regular fa-envelope"></i>お問い合わせ</li>
  </ul>
  <p class="copyright">&copy; 2023 kyokudashi</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark pt-2 pb-2 shadow">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <!--ロゴの設定-->
  <div class="navbar-brand text-light ml-4 mr-5">
    <% if admin_signed_in? %>
      <%= link_to admin_top_path do %>
        <%= image_tag 'logo.png', :size =>'90x60' %>
      <% end %>
    <% else %>
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', :size =>'90x60' %>
      <% end %>
    <% end %>
  </div>
  
  <!--ログイン名表示-->
  <div class="navbar-brand text-light ml-3">
    <% if admin_signed_in? %>
      <b>管理者アカウント</b>
    <% elsif current_user.present? %>
      <b>こんにちは、<%= current_user.name %>さん！</b>
    <% else %>
      <b>こんにちは、ゲストさん！</b>
    <% end %>
  </div>
  
  <!--ナビゲーションバーの表示-->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto mr-auto">
      <li class="nav-item active mr-3">
        <% if current_user.present? %>
          <%= link_to user_path(current_user.id), class: "link" do %>
            <i class="fa-solid fa-user"></i> マイページ
          <% end %>
        <% else %>
        <% end %>
      </li>
  
      <% if current_user.present? %>
        <li class="nav-item active mr-3">
          <%= link_to new_music_path, class: "link" do %>
            <i class="fa-solid fa-music"></i> 新規曲出し
          <% end %>
        </li>
        <% if Music.exists?(user_id: current_user.id) == true %>
          <li class="nav-item active mr-5">
            <% @music = Music.find_by(user_id: current_user.id) %>
            <%= link_to music_path(@music), class: "link" do %>
              <i class="fa-solid fa-music"></i> マイ曲出し
            <% end %>
          </li>
        <% else %>
        <% end %>
      <% else %>
      <% end %>
  
      <% if admin_signed_in? %>
        <li class="nav-item active mr-3">
          <%= link_to admin_musics_path, class: "link" do %>
            <i class="fa-solid fa-headphones"></i> 曲出し一覧
          <% end %>
        </li>
        <li class="nav-item active mr-3">
          <%= link_to admin_users_path, class: "link" do %>
            <i class="fa-solid fa-people-group"></i> ユーザー一覧
          <% end %>
        </li>
        <li class="nav-item active mr-5">
          <%= link_to admin_bands_path, class: "link" do %>
            <i class="fa-solid fa-guitar"></i> バンド一覧
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to timetable_admin_musics_path, class: "link" do %>
            <i class="fa-regular fa-clock"></i> タイムテーブル
          <% end %>
        </li>
      <% else %>
        <li class="nav-item active mr-3">
          <%= link_to musics_path, class: "link" do %>
            <i class="fa-solid fa-headphones"></i> 曲出し一覧
          <% end %>
        </li>
        <li class="nav-item active mr-3">
          <%= link_to users_path, class: "link" do %>
            <i class="fa-solid fa-people-group"></i> ユーザー一覧
          <% end %>
        </li>
        <li class="nav-item active mr-3">
          <%= link_to bands_path, class: "link" do %>
            <i class="fa-solid fa-guitar"></i> バンド登録/一覧
          <% end %>
        </li>
      <% end %>
    </ul>
  
    <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn rounded-pill btn-outline-light text-danger' do %>
          <i class="fa-solid fa-right-from-bracket"></i> LOGOUT
        <% end %>
      <% elsif user_signed_in? %>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn rounded-pill btn-outline-light text-danger' do %>
            <i class="fa-solid fa-right-from-bracket"></i> LOGOUT
          <% end %>
        </li>
      <% else %>
        <li class="nav-item mr-3">
          <%= link_to new_user_registration_path, class: 'btn rounded-pill btn-outline-light text-info' do %>
            <i class="fa-solid fa-user-plus"></i> SIGN UP
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: 'btn rounded-pill btn-outline-light text-success' do %>
            <i class="fa-solid fa-right-to-bracket"></i> SIGN IN
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kyokudashi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/375332867e.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>